### ISSUE TITLE
README.md Npm wrong command

### ISSUE THREAD

**Issue by yagyesh-bobde** [Outerbase/ezql#26]
In the README.md file the command is npm add but it should be npm install

## Files To Update
https://github.com/Outerbase/ezql/blob/main/README.md

**Comment by Brayden** [comment]
Thanks for raising an issue @yagyesh-bobde. Both `npm add` and `npm install` are aliases and execute the same. Previously one would use the `--save` but that is now deprecated as well.

Closing the issue but if you have more information as to why one is superior to the other please do open another for discussion!
